services:
  backend:
        restart: always
        build:
                context: ../
                dockerfile: Dockerfile
        container_name: backend-server
        ports:
                - "8000:8000"
        env_file:
                - .env
        
