[theme]
primaryColor="#F63366"
backgroundColor="#101010"
secondaryBackgroundColor="#101010"
textColor="#f5f5f5"
font="sans serif"

[client]                                                                                              │faceRecModule  run_server.sh     streamlit_app.py
toolbarMode= "minimal"  